steps:
  - name: 'python'
    entrypoint: 'pip'
    args: ['install', 'twine', 'build', 'keyrings.google-artifactregistry-auth']

  - name: 'python'
    entrypoint: 'python'
    args: ['-m', 'build']

  - name: 'python'
    entrypoint: 'python'
    args:
      - '-m'
      - 'twine'
      - 'upload'
      - '--repository-url'
      - 'https://${_REGION}-python.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/'
      - 'dist/*'
  
substitutions: 
  _REPO_NAME: 'home-ai-ai-python'
  _REGION: 'us-central1'

options:
  logging: CLOUD_LOGGING_ONLY
