steps:
  - name: 'python'
    entrypoint: '/bin/bash' # Use a shell entrypoint
    args:
      - '-c' # Pass the following string as a command to the shell
      - | # Use multi-line string for clarity
        # Install dependencies
        pip install twine build keyrings.google-artifactregistry-auth
        
        # Build the package (same container)
        python -m build
        
        # Upload the package (same container)
        python -m twine upload \
          --repository-url 'https://${_LOCATION}-python.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/' \
          dist/*

substitutions: 
  _REPOSITORY: 'home-ai-ai-python'
  _LOCATION: 'us-central1'

options:
  logging: CLOUD_LOGGING_ONLY
